Makefile, eppo/src/main/java/cloud/eppo/android/EppoClient.java, eppo/src/main/java/cloud/eppo/android/logging/Assignment.java, eppo/src/main/java/cloud/eppo/android/util/Utils.java
Made below changes in the code.
- removed extra `/` from make file 
- Added helper function `generateExperimentKey` to generate experiment key in `Utils`
- Modified the`Assignment` dto class, added two new field featureFlag and allocation.
- Initialise featureFlag and allocation with feature flag key and allocation key respectively while calling assignment log callback.
=> Added allocation id in the assignment logging data

.github/workflows/publish-sdk.yaml, Makefile
- Added new publish command (`publish-release-without-test`) in make file to by pass the test step for now
- Added workflow ymal file
Ran the workflow with incorrect credential to test the setting. It failed at the last step due to incorrect credential.
=> Aadded workflow for publishing SDK

eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
* renames `getJSONAssignment -> getJSONStringAssignment` for clarity and consistency across SDKs
* adds `getParsedJSONAssignment` method returning a `JsonElement` from the `Gson` library
Ran locally against an emulator:
```
> Task :eppo:eppo:connectedDebugAndroidTest
Starting 2 tests on Pixel_7_API_34(AVD) - 14
BUILD SUCCESSFUL in 13s
1 actionable task: 1 executed
```
=> add support for getJSONStringAssignment and getParsedJSONAssignment (FF-918)

settings.gradle
This has been bugging me. I don't think there is anything customer impacting here as we don't publish this SDK into the android app store but I wanted to get the metadata tidied. up.
=> rename project to Eppo SDK

eppo/build.gradle, example/build.gradle
…sdk 33
```
➜  android-sdk git:(main) ./gradlew connectedCheck
> Configure project :eppo
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> Task :eppo:mergeExtDexDebugAndroidTest
ERROR:/Users/leo/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-servlet/9.4.48.v20220622/8a9a53e0aad3f194a4cc9940f7e9d5619254bf62/jetty-servlet-9.4.48.v20220622.jar: D8: com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
ERROR:/Users/leo/.gradle/caches/modules-2/files-2.1/org.eclipse. …
```
=> fix gradlew connectedCheck to run locally; update example app to min sdk 33

.github/workflows/test.yaml, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoHttpClient.java
**Ticket:** [FF-1133 - Harden waiting for RAC request in Android SDK Test](https://linear.app/eppo/issue/FF-1133/harden-waiting-for-rac-request-in-android-sdk-test)
**Motivation:** still getting weird failures (see: https://github.com/Eppo-exp/sdk-test-data/actions/runs/6661079552)
I want more information to make it in the uploaded log, and I noticed we only allow 2 seconds for the RAC request to finish and then silently continue on our way. This change increases the timeout to be more generous and throws an error if it does time out, so we're not left scratching our heads.
I added a bit of extra logging, too, which revealed that sometimes the action cannot reach the Google Cloud Function. So I added a little loop to wait up to 15 seconds for DNS to resolve before proceeding.
I also saw …
=> Include additional error information in emulator log

.github/workflows/test.yaml, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java
Switches to a Generation 2 Google Cloud Function in the Eppo QA environment.
=> Switch mock RAC server endpoint

eppo/build.gradle
bumping to 1.0.2 in order to publish a new release at that tag; this will include graceful mode to suppress exceptions.
=> bump to 1.0.2

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/RuleEvaluator.java, eppo/src/main/java/cloud/eppo/android/dto/EppoValue.java, eppo/src/test/java/cloud/eppo/android/RuleEvaluatorTest.java
Related implementation to Java (https://github.com/Eppo-exp/java-server-sdk/commit/11c33e30cb7a302edb7082ea42f7695a8a0dc046). Since we are targeting android api 21, we are limited to an older API.
isPresent, which require API level 24 or higher, you'll need to find alternative approaches. The Optional class and its methods were introduced in Java 8, and Android started supporting Java 8 language features from API level 24 onwards. This means methods like isPresent and isEmpty are not directly available on devices running lower API levels.
implementation of semver support using available APIs.
=> Add semver support (FF-1573)

eppo/build.gradle, eppo/src/main/java/cloud/eppo/android/dto/Allocation.java, eppo/src/main/java/cloud/eppo/android/dto/FlagConfig.java, eppo/src/main/java/cloud/eppo/android/dto/RandomizationConfigResponse.java, eppo/src/main/java/cloud/eppo/android/dto/ShardRange.java, eppo/src/main/java/cloud/eppo/android/dto/TargetingCondition.java, eppo/src/main/java/cloud/eppo/android/dto/TargetingRule.java, eppo/src/main/java/cloud/eppo/android/dto/Variation.java
We had an observation from a customer that when they deployed the android SDK to production, while their testing environment behaved appropriated, they immediately saw crashes. 
Tracing through our application code we observed that the `flags` variable was being set to `null`, and then accessed casuing a`java.lang.NullPointerException`:
```
RandomizationConfigResponse config = gson.fromJson(response, RandomizationConfigResponse.class);
flags = config.getFlags();
flags.keySet() # exception!
```
Aaron has a PR (https://github.com/Eppo-exp/android-sdk/pull/38) to be more defensive.
👉 We verified that the response for the RAC API for this customer was well formed and valid.
My hypothesis for why `gson` is not able to deserialize the json payload into a Java object is because in the customer's …
=> Add @SerializedName labels to dto to make json->object mapping explicit. (FF-1869)

.github/workflows/test.yaml, eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigurationRequestor.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
_Eppo Internal:_ 🎟️ **Ticket:** [FF-1869 - crash in android app Attempt to invoke virtual method 'java.util.Set j$.util.concurrent.ConcurrentHashMap.keySet()' on a null object reference](https://linear.app/eppo/issue/FF-1869/crash-in-android-app-attempt-to-invoke-virtual-method-javautilset)
If, for whatever reason, the request for a configuration is technically "successful," but the resulting JSON object is missing the `flags` property, it will result in a downstream error.
To resolve this--and allow future polls to set the flags--we treat it as having received an empty list of flags.
=> Handle missing flags in a valid JSON configuration request

.github/workflows/publish-sdk.yaml, .github/workflows/test.yaml, Makefile, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java
To speed up these tests, I followed the suggestions in the [emulator runner action](https://github.com/marketplace/actions/android-emulator-runner) we use. It mainly said to use Ubuntu, enable acceleration, and try to cache Gradle and the Image.
To de-flake, I now clear SharedPreferences between tests (if we blow away the file cache too). My suspicion is that we were storing a bad (perhaps mocked) config in there that would mess up a later test until it fetched an updated config.
🔥 🔥 🔥 🔥 🔥 🔥
=> Speed-up and de-flake our tests

.github/workflows/test.yaml, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/CacheLoadCallback.java, eppo/src/main/java/cloud/eppo/android/ConfigurationRequestor.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java, eppo/src/main/java/cloud/eppo/android/dto/Allocation.java, eppo/src/main/java/cloud/eppo/android/dto/FlagConfig.java, eppo/src/main/java/cloud/eppo/android/dto/OperatorType.java, eppo/src/main/java/cloud/eppo/android/dto/RandomizationConfigResponse.java, eppo/src/main/java/cloud/eppo/android/dto/ShardRange.java, eppo/src/main/java/cloud/eppo/android/dto/TargetingCondition.java, eppo/src/main/java/cloud/eppo/android/dto/TargetingRule.java, eppo/src/main/java/cloud/eppo/android/dto/Variation.java, eppo/src/main/java/cloud/eppo/android/dto/deserializers/EppoValueAdapter.java, eppo/src/main/java/cloud/eppo/android/dto/deserializers/RandomizationConfigResponseDeserializer.java, eppo/src/test/java/cloud/eppo/android/EppoValueDeserializerTest.java, eppo/src/test/java/cloud/eppo/android/RandomizationConfigResponseDeserializerTest.java, example/build.gradle, example/src/main/java/cloud/eppo/androidexample/EppoApplication.java
_Eppo Internal:_ 🎟️ **Ticket:** [FF-1892 - Android SDK Handle loading flags when using ProGuard minification](https://linear.app/eppo/issue/FF-1892/android-sdk-handle-loading-flags-when-using-proguard-minification)
Our existing JSON deserialization leveraged `gson`'s automatic mapping of JSON fields to Java Object properties based on their names. However, this would fail when those property names changed due to minification, such as by ProGuard. 
To get around this without the need to modify `proguard-rules.pro` (which could be at best burdonsome and at worst fragile), we explicitly define a deserializer and use that to parse the configuration response.
This was tested by building the example application with minification enabled. Before the changes, it didn't get assignments, but now it …
=> Handle being able to be minified by ProGuard

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigurationRequestor.java
There is one spot--where we successfully load the configuration from the file cache--where we don't check if the initialization callback is defined before attempting to call it. This adds in that check.
=> Handle if null initialization callback

eppo/build.gradle, eppo/src/main/java/cloud/eppo/android/EppoClient.java, eppo/src/main/java/cloud/eppo/android/logging/Assignment.java, eppo/src/main/java/cloud/eppo/android/util/Utils.java, eppo/src/test/java/cloud/eppo/android/UtilsTest.java
the timestamp in the assignment logger was receiving strings in a locale format: `'٢٠٢٤-٠٤-١٢T٢٣:٤٥:٠١Z'`
* Ensure that `Utils.getISODate()` explicitly overrides the device's local to `Locale.US`
* Unit tests
* Format touched files according to java style-guide
=> Ensure assignment date is in ISO8601 format (FF-1933)

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigCacheFile.java, eppo/src/main/java/cloud/eppo/android/ConfigurationRequestor.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java, eppo/src/main/java/cloud/eppo/android/logging/Assignment.java, eppo/src/main/java/cloud/eppo/android/util/Utils.java
🎟️ **Ticket:** [FF-2092 - Cache should not succeed unless loaded flags & SDK key specific](https://linear.app/eppo/issue/FF-2092/cache-should-not-succeed-unless-loaded-flags-and-sdk-key-specific)
🗨️ **Slack Convo:** ["...There should be no race between SDK initialization and assignment..."](https://eppo-group.slack.com/archives/C0641KPCHP1/p1715789340639449?thread_ts=1714458577.930229&cid=C0641KPCHP1)
A user noticed an apparent race condition between initialization and assignment.
What is happening is that the client _thinks_ it successfully populated from a cached configuration, but that configuration is empty. It fires off the completion callback before fetching an updated configuration. Then `getAssignment()` is called with the empty configuration before the correct …
=> Better cache initialization

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigurationRequestor.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
🎟️ **Ticket:** [FF-2111 - Android SDK should initialize with fetched data if it finishes before the cache load](https://linear.app/eppo/issue/FF-2111/android-sdk-should-initialize-with-fetched-data-if-it-finishes-before)
🗨️ **Slack Conversation:** ["...Race condition between cache access/http request?..."](https://eppo-group.slack.com/archives/C0641KPCHP1/p1715959937521589?thread_ts=1714458577.930229&cid=C0641KPCHP1)
While typically, one would expect file systems to be quicker than HTTP, this is not _guaranteed_. Especially if emulation is at play, the storage speed is slowed (encrypted, degraded), etc.
If the cache load finishes _after_ the configuration fetch, it is possible it may unintentionally overwrite that newly-obtained configuration with a cached, older version. …
=> Handle configuration fetching vs. cache race condition

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigurationRequestor.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java, eppo/src/main/java/cloud/eppo/android/EppoHttpClient.java, eppo/src/main/java/cloud/eppo/android/dto/adapters/EppoValueAdapter.java, eppo/src/main/java/cloud/eppo/android/dto/adapters/RandomizationConfigResponseAdapter.java, eppo/src/test/java/cloud/eppo/android/EppoValueAdapterTest.java, eppo/src/test/java/cloud/eppo/android/RandomizationConfigResponseAdapterTest.java
🎟️ **ticket:** [FF-2159 - Android SDK Needs a custom serializer to handle code minification](https://linear.app/eppo/issue/FF-2159/android-sdk-needs-a-custom-serializer-to-handle-code-minification)
If ProGuard is used, then Gson won't serialize flag configurations with known field names. To get around this, we should just write the JSON file exactly as we received it.
Verified fix checking the logs of our example app, which has its source minified using ProGuard.
_Before:_
```
Loading from cache
Error loading from local cache
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.gson.JsonElement.getAsInt()' on a null object reference
```
_After:_
```
Loading from cache
Cache loaded successfully
Initialized from cache
```
=> Save cache file as received rather than serializing it again

eppo/src/main/java/cloud/eppo/android/EppoClient.java
Hi guys, an Android dev here. Recently we have started using your Android SDK in our app and noticed that there is no possibility to refresh the configuration after the app initialization, because the function 'refreshConfiguration' is private.
Sometimes we may need to refresh the configuration during the app's session. Could you make this method public so we would be able to refresh the configuration when needed? It is possible in iOS SDK, so I assume it could be possible in Android SDK as well?
Best,
Pawel
=> External request - make 'EppoClient.refreshConfiguration' public

eppo/build.gradle, eppo/src/main/java/cloud/eppo/android/EppoClient.java
🎟️ **Ticket:** [FF-2305](https://linear.app/eppo/issue/FF-2305/android-sdk-prep-and-release-booksy-change-to-make-loading-config)
To release external change request #52, which exposes `EppoClient`s `refreshConfiguration()` method, we want to bump the version and add a `@Deprecated` annotation.
The reason to flag it as `@Deprecated` out the gate is that this particular method--previously only used on initialization--also does some cache-loading stuff. Ideally, we'd pull out the HTTP stuff into a standalone public refresh method. That being said, this newly-exposed method will still accomplish a refresh. It will load whatever was previously fetched from the cache and update it when the fetch completes. However, it's a roundabout way that does more work than it has to, and …
=> Pepare making 'EppoClient.refreshConfiguration' public for release

.github/workflows/publish-sdk.yaml, .github/workflows/test.yaml
In #50 I changed the publish workflow to also test before publishing. This is a change we want. However, it fails because that workflow doesn't set up the emulated environment.
To fix this, I've changed things so that the publish workflow first calls the test workflow, leveraging GitHub's ability to [reuse workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows). I've made it so the publish job [depends on](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs) the test job succeeding.
=> Reuse test workflow for publishing

eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
This is the same as `getJSONAssignment` but returns a json `String` instead of a parsed `JSONObject`
=> feat: Add `getJSONStringAssignment` API method

.github/workflows/publish-sdk.yaml, .github/workflows/publish-snapshot.yml, eppo/build.gradle
This looks like a behavior change with Android Gradle plugin v8 as documented [here](https://stackoverflow.com/questions/71365373/software-components-will-not-be-created-automatically-for-maven-publishing-from/71366104#71366104)
This should fix the issue so that artifacts are properly uploaded with the release.
Verified locally by creating a separate repository and importing the `3.2.0-SNAPSHOT` into it with this code
=> fix: Publish build artifacts with release

eppo/build.gradle, example/src/main/java/cloud/eppo/androidexample/SecondActivity.java
This fixes an issue where users of `android-sdk` couldn't reference classes from `sdk-common-jvm` like `SubjectAttributes` because they were not exposed.
More info on the differences: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
=> fix: Export `sdk-common-jvm` to consumers of `android-sdk`

README.md
This is a temporary fix while I get us out of the snapshot version of `sdk-common-jvm` - will have a PR for that as soon as I release v2 of that
=> fix: Update README usage instructions

eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java
* Replace `AsyncTask` (deprecated) with `Executors.newSingleThreadExecutor()`
* Use proper synchronization lock
* Use try-with-resources to make sure `BufferedWriter` is closed
=> fix: Configuration store minor fixes

.github/workflows/test.yaml
🎟️ Fixes FF-3091 towards FF-3085
👯‍♂️ **Related PRs**
- [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data/pull/59)
- [react-native-sdk](https://github.com/Eppo-exp/react-native-sdk/pull/58)
- [golang-sdk](https://github.com/Eppo-exp/golang-sdk/pull/66)
- [ios-sdk](https://github.com/Eppo-exp/eppo-ios-sdk/pull/40)
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). …
=> quality: parameterize SDK and test data branches

.github/workflows/test.yaml
Tests are automatically failing from using a deprecated version of actions/upload-artifact.
[Deprecation Notice](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)
failing tests
Now running & passing tests
=> chore: upgrade from deprecated version of actions/upload-artifact

.github/workflows/publish-snapshot.yml
This new plugin expects the username and password env vars to be `mavenCentralUsername` and `mavenCentralPassword` instead
=> fix: Rename publish username/password

README.md, eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java, example/src/main/java/cloud/eppo/androidexample/SecondActivity.java
Better Developer Experience
- cleaner Builder initialization (put required fields in the constructor)
- only allow obfuscated configuration to be passed
=> feat: better DX

.github/workflows/test.yaml, eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/ConfigurationStore.java, eppo/src/main/java/cloud/eppo/android/util/Utils.java, example/build.gradle, example/src/main/java/cloud/eppo/androidexample/MainActivity.java, example/src/main/java/cloud/eppo/androidexample/SecondActivity.java, example/src/main/res/layout/activity_main.xml
[Jackson v2.13](https://github.com/FasterXML/jackson/wiki/Jackson-Releases) [dropped](https://github.com/FasterXML/jackson-module-kotlin/issues/716#issuecomment-1765071697) support for Android version below 26, so this was just instacrashing on Android 24 and 25 with:
```
Process: cloud.eppo.androidexample, PID: 4545
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/BootstrapMethodError;
at com.fasterxml.jackson.databind.util.ExceptionUtil.isFatal(ExceptionUtil.java:51)
at com.fasterxml.jackson.databind.util.ExceptionUtil.rethrowIfFatal(ExceptionUtil.java:31)
at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:70)
at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:402)
at …
```
=> fix: Bump minSdk version to 26

.github/workflows/publish-sdk.yaml
I did this for `publish-snapshot` but forgot to do the same for `publish-sdk`
=> fix: Rename sonatype credentials var

eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
There are certain circumstances when we want to suppress loading Configuration from the filesystem cache.
- `IgnoreConfigurationCache` method.
=> feat: Allow ignoring the cached configuration

eppo/build.gradle
=> chore: bump version for next snapshot

eppo/build.gradle
For local builds signing, we use the following in the `~/gradle/gradle.properties` file:
```
signing.keyId=12345678
signing.password=some_password
signing.secretKeyRingFile=/Users/yourusername/.gnupg/secring.gpg
```
However, for CI builds we use in-memory PGP keys from `GPG_PRIVATE_KEY` and `GPG_PASSPHRASE`. This used to work well, but since we moved to `com.vanniktech.maven.publish` it looks like this functionality broke CI release publishing.
This logic ensures that we can use one or the other depending on whether the env vars are present
1. Local GPG
```
./gradlew eppo:signMavenPublication                                                                                                                                     
> Configure project :eppo
using local GPG
BUILD SUCCESSFUL in …
```
=> fix(build): Allow signing build with in memory PGP keys

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
fixes: FF-3751
Due to the sensitive nature of the client configuration payload, the decision was made to support only obfuscated configuration in the Android SDK through its standard initialization method. This decision was made _prior_ to the introduction of the `format` field in `FlagConfigResponse`. This was short-sighted as
1. This is a popular development approach
2. The configuration payload now contains the `format` field which can be used to determine the format of the configuration.
- migrated the client init entry points to call into the `Configuration.Builder` without forcing `isConfigObfuscated` to `true`
- tests
- deprecated methods where `isConfigObfuscated` can be provided in the jvm-common-sdk
=> fix: allow offline init with unobfuscated config

README.md, eppo/build.gradle, eppo/src/main/java/cloud/eppo/android/EppoClient.java
towards FF-3558
🎟️ [FF-3558](https://linear.app/eppo/issue/FF-3558/unify-sdk-request-baseurl)
Most, nearly all in fact, of the SDKs use a baseUrl of https://fscdn.eppo.cloud/api and endpoint constants of `/flag-config/v1/config` and `/flag-config/v1/bandits` for flag and bandit requests.
All of the SDKs need to follow the common convention in order for our cross-SDK testing tools (scenario testing, benchmarking) to work seamlessly.
=> chore: latest from the common package and move `/api` to baseUrl

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java, example/src/main/java/cloud/eppo/androidexample/SecondActivity.java
Getting periodic flag configuration updates to mobile app SDKs has not been a priority since the session lengths are generally pretty low. To bring more feature parity across the Java SDKs, we seek to expose polling functionality and configuration options to the android SDK
- expose polling params in the client builder
- start polling after init, if polling is enabled in the builder
- surface pause/resume methods so polling can hook into the application/activity's lifecycle
[FF-3923](https://linear.app/eppo/issue/FF-3923/[docs]-update-android-documentation)
[eppo-docs#588](https://github.com/Eppo-exp/eppo-docs/pull/588-detailing-polling-configuration)
=> feat: Allowing polling in Android mobile client

eppo/build.gradle, eppo/src/androidTest/java/cloud/eppo/android/EppoClientTest.java, eppo/src/main/java/cloud/eppo/android/EppoClient.java
Fixes FF-4031
On mobile applications, it is useful to reload the configuration on-demand since polling is not typically employed.
Override the `loadConfiguration` and `loadConfigurationAsync` methods on the `EppoClient`, delegating to the super class methods.
New unit tests
=> feat: Make loadConfiguration public

eppo/src/main/java/cloud/eppo/android/EppoClient.java
[//]: #  I want to keep showing archived feature flags. I will make a custom `ConfigurationStore` to do that and will merge the last-seen feature flag there.
[//]: # Make `cloud.eppo.android.EppoClient.Builder.configStore()` public so I can customize `ConfigurationStore`
[//]: # I didn't.
[//]: # I didn't test this because it has no impact on the product.
=> Make EppoClient.Builder.configStore() public

.github/workflows/test.yaml
[//]: #  (Link to the issue corresponding to this chunk of work)
:tickets: [FFL-432 - Include API Version 28 (Android 9) In Matrix Test](https://datadoghq.atlassian.net/browse/FFL-432?atlOrigin=eyJpIjoiOTU4ZTE5NzFlNjY5NGViZmJhZmIwNmUxYWRlYmM5NzciLCJwIjoiaiJ9)
🗨️ Relevant slack: ["...Android 9 devices..."](https://eppo-group.slack.com/archives/C08B4L9G2N9/p1752526190798449)
We'd like to explicitly test Android 9
Add API Version 28 to test matrix
_n/a_
The tests themselves!
=> Include api level 28 in test matrix
